- ansible.builtin.include_role:
    name: beryjuio_containerd
  vars:
    beryjuio_containerd_profile: kubernetes
- ansible.builtin.import_tasks: system.yml
- ansible.builtin.import_tasks: package.yml
