- name: docker | install pre-dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  register: apt_res
  retries: 5
  until: apt_res is success
- name: docker | apt repo
  ansible.builtin.deb822_repository:
    name: docker
    uris: "https://download.docker.com/linux/ubuntu"
    types: [deb]
    suites: [jammy]
    components: [stable]
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
    enabled: true
  notify:
    - Apt update
- ansible.builtin.meta: flush_handlers
- name: docker | containerd package
  ansible.builtin.apt:
    pkg:
      - "containerd.io"
  register: apt_res
  retries: 5
  until: apt_res is success
- name: containerd | docker package
  ansible.builtin.apt:
    pkg:
      - "docker-ce"
      - "docker-compose-plugin"
  when: "beryjuio_containerd_profile == 'docker'"
  register: apt_res
  retries: 5
  until: apt_res is success
- name: docker | containerd config
  when: "beryjuio_containerd_profile == 'kubernetes'"
  ansible.builtin.template:
    src: "templates/containerd.toml"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "644"
  notify:
    - Restart containerd
