- name: authentik | install pre-dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  register: apt_res
  retries: 5
  until: apt_res is success
- name: authentik | apt repo
  ansible.builtin.deb822_repository:
    name: authentik
    uris: "https://pkg.goauthentik.io"
    types: [deb]
    suites: [stable]
    components: [main]
    signed_by: https://pkg.goauthentik.io/keys/gpg-key.asc
    state: present
    enabled: true
  notify:
    - Apt update
- name: authentik | system agent
  ansible.builtin.apt:
    pkg:
      - authentik-sysd
      - libnss-authentik
      - libpam-authentik
    state: present
- name: authentik | join domain
  ansible.builtin.command:
    cmd: ak-sysd domains join ak --authentik-url https://id.beryju.io
    stdin: '{{ lookup("community.hashi_vault.hashi_vault", "secret=kv/data/authentik/endpoint-server-prod:key") }}'
    creates: /etc/authentik/domains/ak.json
